### ISSUE TITLE
fork todo

### ISSUE THREAD

**Issue by clod-mc** [clod-mc/PortalNetwork#1]
- [x] remove publishing
- [x] amend readme to indicate that it's a fork
- [x] vendor bcf
- [x] switch to gradle (ensure jar naming contains `Clod`)
- [x] google-java-format
- [x] use commit date version scheme
- [x] makefile w/ python venv management
- [x] checkstyle (google without `MissingSwitchDefault`, `Indentation`, `AbbreviationAsWordInName`, `MissingJavadocMethod`, `MissingJavadocType`; add checks to prevent `TODO`, `var`, `AvoidStaticImport`, and `EmptyStatementCheck`)
- [x] address linting issues
- [x] publish release to github w/ actions
